In [17]:
import pandas as pd

In [18]:
INPUT_FILE = r"../data/drug_consumption_transformed.csv"
OUTPUT_FILE = r"../data/drug_consumption_numeric.csv"

In [19]:
df = pd.read_csv(INPUT_FILE)
df

,age,gender,education,country,ethnicity,nscore,escore,oscore,ascore,cscore,choc
0,35-44,Male,University degree,Canada,Mixed-White/Black,39,36,42,37,42,CL5
1,25-34,Female,Left school,Canada,Mixed-Black/Asian,29,52,55,48,41,CL6
2,35-44,Female,University degree,Canada,Mixed-Black/Asian,31,45,40,32,34,CL4
3,18-24,Male,Professional certificate/diploma,Canada,Mixed-Black/Asian,34,34,46,47,46,CL4
4,35-44,Male,Left school,Canada,Mixed-Black/Asian,43,28,43,41,50,CL6
...,...,...,...,...,...,...,...,...,...,...,...
1880,18-24,Male,Masters degree,UK,Mixed-Black/Asian,25,51,57,48,33,CL4
1881,18-24,Female,Masters degree,UK,Mixed-Black/Asian,33,51,50,48,30,CL4
1882,25-34,Male,Doctorate degree,UK,Mixed-Black/Asian,47,30,37,31,31,CL6
1883,18-24,Male,Masters degree,UK,Mixed-Black/Asian,45,26,48,32,22,CL5
1884,18-24,Female,Masters degree,Republic of Ireland,Mixed-Black/Asian,31,53,56,50,45,CL6

In [20]:
COLUMN_ORDERS = {
    "age": ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
    "education":  ["Left school", "Some college or university, no certificate or degree", "Professional certificate/diploma",
                    "University degree", "Masters degree", "Doctorate degree"],
    "choc": [f"CL{i}" for i in range(7)]
}

In [22]:
for col, orders in COLUMN_ORDERS.items():
    n_levels = len(orders)
    mapping = dict(zip(orders, range(n_levels)))
    df[col] = df[col].map(mapping)
df

,age,gender,education,country,ethnicity,nscore,escore,oscore,ascore,cscore,choc
0,2,Male,3,Canada,Mixed-White/Black,39,36,42,37,42,5
1,1,Female,0,Canada,Mixed-Black/Asian,29,52,55,48,41,6
2,2,Female,3,Canada,Mixed-Black/Asian,31,45,40,32,34,4
3,0,Male,2,Canada,Mixed-Black/Asian,34,34,46,47,46,4
4,2,Male,0,Canada,Mixed-Black/Asian,43,28,43,41,50,6
...,...,...,...,...,...,...,...,...,...,...,...
1880,0,Male,4,UK,Mixed-Black/Asian,25,51,57,48,33,4
1881,0,Female,4,UK,Mixed-Black/Asian,33,51,50,48,30,4
1882,1,Male,5,UK,Mixed-Black/Asian,47,30,37,31,31,6
1883,0,Male,4,UK,Mixed-Black/Asian,45,26,48,32,22,5
1884,0,Female,4,Republic of Ireland,Mixed-Black/Asian,31,53,56,50,45,6

In [23]:
df.to_csv(OUTPUT_FILE, index = False)